/** Brand catalogs for logo clouds — slugs map to simple-icons (or BrandIcon fallbacks). */

export const AI_MODEL_LOGOS = [
    { slug: "openai", label: "OpenAI" },
    { slug: "anthropic", label: "Anthropic" },
    { slug: "claude", label: "Claude" },
    { slug: "googlegemini", label: "Google Gemini" },
    { slug: "huggingface", label: "Hugging Face" },
    { slug: "ollama", label: "Ollama" },
    { slug: "mistralai", label: "Mistral AI" },
    { slug: "deepseek", label: "DeepSeek" },
    { slug: "perplexity", label: "Perplexity" },
    { slug: "meta", label: "Meta" },
    { slug: "langchain", label: "LangChain" },
    { slug: "langgraph", label: "LangGraph" },
];

export const INTEGRATION_LOGOS = [
    { slug: "whatsapp", label: "WhatsApp" },
    { slug: "slack", label: "Slack" },
    { slug: "shopify", label: "Shopify" },
    { slug: "googlesheets", label: "Google Sheets" },
    { slug: "googledrive", label: "Google Drive" },
    { slug: "googledocs", label: "Google Docs" },
    { slug: "googleforms", label: "Google Forms" },
    { slug: "notion", label: "Notion" },
    { slug: "airtable", label: "Airtable" },
    { slug: "hubspot", label: "HubSpot" },
    { slug: "zapier", label: "Zapier" },
    { slug: "n8n", label: "n8n" },
    { slug: "make", label: "Make" },
    { slug: "twilio", label: "Twilio" },
    { slug: "stripe", label: "Stripe" },
    { slug: "instagram", label: "Instagram" },
    { slug: "telegram", label: "Telegram" },
    { slug: "googlecloud", label: "Google Cloud" },
    { slug: "amazonwebservices", label: "AWS" },
    { slug: "microsoftazure", label: "Azure" },
    { slug: "vercel", label: "Vercel" },
    { slug: "docker", label: "Docker" },
    { slug: "kubernetes", label: "Kubernetes" },
    { slug: "postgresql", label: "PostgreSQL" },
    { slug: "redis", label: "Redis" },
    { slug: "mongodb", label: "MongoDB" },
    { slug: "supabase", label: "Supabase" },
    { slug: "fastapi", label: "FastAPI" },
    { slug: "python", label: "Python" },
    { slug: "react", label: "React" },
    { slug: "nextdotjs", label: "Next.js" },
    { slug: "nodedotjs", label: "Node.js" },
    { slug: "qdrant", label: "Qdrant" },
    { slug: "elasticsearch", label: "Elasticsearch" },
    { slug: "temporal", label: "Temporal" },
    { slug: "grafana", label: "Grafana" },
    { slug: "prometheus", label: "Prometheus" },
    { slug: "sentry", label: "Sentry" },
    { slug: "github", label: "GitHub" },
];

/** Map free-text stack labels → icon slug */
export const STACK_ICON_MAP = {
    "OpenAI (GPT-5.x)": "openai",
    "GPT-5": "openai",
    "Anthropic (Claude Sonnet / Haiku)": "anthropic",
    "Claude Sonnet": "claude",
    "Google (Gemini)": "googlegemini",
    "Open-weights via vLLM / TGI": "huggingface",
    LangGraph: "langgraph",
    LangChain: "langchain",
    LlamaIndex: "python",
    "Custom Python runtimes": "python",
    Temporal: "temporal",
    pgvector: "postgresql",
    Qdrant: "qdrant",
    Weaviate: "python",
    "Elasticsearch (hybrid)": "elasticsearch",
    FastAPI: "fastapi",
    "Node.js": "nodedotjs",
    Postgres: "postgresql",
    PostgreSQL: "postgresql",
    Redis: "redis",
    "Next.js": "nextdotjs",
    React: "react",
    "Tailwind CSS": "tailwindcss",
    "shadcn/ui": "react",
    AWS: "amazonwebservices",
    GCP: "googlecloud",
    Vercel: "vercel",
    "Docker + Kubernetes": "docker",
    Docker: "docker",
    Kubernetes: "kubernetes",
    OpenTelemetry: "opentelemetry",
    "Langfuse / LangSmith": "langchain",
    "Prometheus + Grafana": "grafana",
    Sentry: "sentry",
    WhatsApp: "whatsapp",
    "WhatsApp Business": "whatsapp",
    Shopify: "shopify",
    Twilio: "twilio",
    "Instagram API": "instagram",
    Python: "python",
    RAG: "huggingface",
    "Carrier APIs": "amazonwebservices",
    "CRM API": "hubspot",
    "Booking API": "googlecalendar",
    "Custodian APIs": "googlesheets",
    "BIM metadata": "googledrive",
    "Tablet UI": "react",
    "Chat UI": "react",
    "Ground-truth QA sets": "pytest",
    "LLM-as-judge (calibrated)": "openai",
    "Cost + latency budgets": "grafana",
    "Regression suites in CI": "github",
};

export function stackIconSlug(label) {
    return STACK_ICON_MAP[label] || null;
}
